### ISSUE TITLE
[Performance] Temps d'espera exponencial

### ISSUE THREAD

**Issue by alex-pelaez** [amurgo/TrailRunningRaces#4]
Funció per a decidir el temps d'espera a partir de:
- Codi HTTP de la resposta
- Temps de resposta
- Número d'instàncies

Ex: Si rebo un HTTP code diferent de 200 incremento el temps un 10%. Si rebo N (número d'instàncies) igual a 200 seguits redueixo un 10%.

**Comment by amurgo** [comment]
De moment no sembla necessari.

**Comment by alex-pelaez** [comment]
No cal.
